micronaut:
  application:
    name: micronautAerospikeDemo

  email:
    from:
      email: abhipatil7038@gmail.com
      name: Customer Care
  security:
    authentication: bearer
    intercept-url-map:
        - pattern: /**/swagger/**
          httpMethod: GET
          access:
            - isAnonymous()
        - pattern: /**/swagger-ui/**
          httpMethod: GET
          access:
            - isAnonymous()
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: 'cGxlYXNlQ2hhbmdlVGhpc1NlY3JldEZvckFOZXdPbmU='
              base64: true
              jws-algorithm: HS256
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**



aerospike:
  host: 127.0.0.1
  port: 3000
  namespace: test
netty:

    default:
      allocator:
        max-order: 3

javamail:
  properties:
    mail:
      smtp:
        port: 587
        auth: true
        starttls:
          enable: true
        host: smtp.gmail.com
  authentication:
    username: abhipatil7038@gmail.com
    password: vojbuukdqgwpdvop

kafka:
  bootstrap:
    servers: localhost:9092